<a href="https://colab.research.google.com/github/jangInw007/A4-Data-Analytics-and-Modeling/blob/main/Copy_of_PJ2_Group_A4_Data_Analytics_and_Modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mini Project 2: Data Analytics and Modeling

<img src="https://datarundown.com/wp-content/uploads/2023/05/Model-Data-Analytics.jpg" width="400px">

ชื่อกลุ่ม: A4

รายชื่อสมาชิก การแบ่งงาน และสัดส่วนในการทำงาน:
1. นางสาวกฤตยา นิกรกุล 663020277-7
2. นางสาวจิตรลดา นิมินรัมย์ 663020278-5
3. นางสาวบงกช เจตวัน 663020284-0
4. นายรุ่งแสง กองสุข 663020292-1

กำหนดส่ง: ศุกร์ 24 ตุลาคม 2568  

รายงานในชั้นเรียน: เสาร์ 25 ตุลาคม 2568

** NOTE **
* อย่าลืมบันทึกงานที่ทำในโน้ตบุ๊คนี้เป็นประจำขณะทำงาน มิเช่นนั้นงานที่ทำอยู่อาจสูญหายได้
* **เริ่มทำแต่เนิ่น ๆ อย่ารอที่จะทำก่อนส่ง เพราะจะทำไม่เสร็จ เนื่องจากปัญหามากมายที่จะเกิดขึ้นระหว่างการทำงาน และอาจารย์ไม่รับปรึกษาในคืนก่อนส่ง**
----------------------

### เลือกชุดข้อมูล 1 ชุดจากข้อมูลที่กำหนดให้ต่อไปนี้
* <b>MovieLens 1M Data Set<b>
    * ข้อมูลชุดนี้มีข้อมูลเกี่ยวกับ movies, users, และ how they rate the movies
    * สามารถดูรายละเอียดได้ที่ http://grouplens.org/datasets/movielens/
    * Download the 1 million ratings data set from https://grouplens.org/datasets/movielens/1m/
    * Merge all of the data into a single Pandas DataFrame. See
        * https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.merge.html
    
* <b>Walmart_Sales_Forecast<b>
    * สามารถดูรายละเอียดได้ที่ https://github.com/Asikpalysik/Walmart_Sales_Forecast/tree/main
    * ข้อมูลประกอบด้วยไฟล์ features.csv, stores.csv และ ข้อมูลยอดขาย (train.csv และ test.csv)
    * ให้ใช้ข้อมูลจากทุกไฟล์ทุกอย่างประกอบกันในการวิเคราะห์
    
* <b>NYC Taxi Trips<b>
    * ข้อมูลทริปของแท็กซี่ในเมืองนิวยอร์กจาก https://www.nyc.gov/site/tlc/about/tlc-trip-record-data.page
    * ข้อมูลเก็บโดย The NYC Taxi and Limousine Commission (TLC) ประกอบด้วย pick-up and drop-off dates/times, pick-up and drop-off locations, trip distances, itemized fares, rate types, payment types, and driver-reported passenger counts
    * นอกจากไฟล์ข้อมูลทริปของแท็กซี่แล้ว ยังมีข้อมูลเกี่ยวกับ zone ของพื้นที่ที่ให้บริการ และคำอธิบายข้อมูลในส่วนล่างสุดของหน้าเดียวกัน
    * ให้ศึกษาข้อมูลการเดินทางของแท็กซี่เหลืองหรือแท็กซี่เขียวในช่วงหนึ่ง (เช่น 1 เดือน หรือ 1 ปีที่ผ่านมา เป็นต้น)
    * ตัวอย่างการอ่านไฟล์ parquet
    ```python
    # install this module to read .parquet files
    !pip install pyarrow
    import pyarrow.parquet as pq
    trips = pq.read_table('yellow_tripdata_2023-09.parquet')
    trips = trips.to_pandas()
    trips
    ```
    
----------------------------------

### ศึกษาข้อมูลที่เลือกใช้ แล้วทำการ
* Tell story about data อธิบายลักษณะของข้อมูล ทำความเข้าใจเกี่ยวกับข้อมูลชุดนี้ ด้วยสถิติ และนำเสนอด้วยแผนภาพ แผนภูมิ หรือกราฟต่าง ๆ
* ตั้ง<span style="color:red">*ปัญหาหรือคำถามเชิงองค์กรหรือธุรกิจ*</span>ที่กลุ่มท่านสนใจเกี่ยวกับข้อมูลนี้ แล้วทำการคาดการณ์ (conjectures) เกี่ยวกับ<span style="color:red">*ปัญหาหรือคำถาม*</span>ที่ได้ตั้งไว้อย่างน้อย 3 ข้อ แล้วสนับสนุนหรือปฏิเสธข้อคาดการณ์ด้วยการวิเคราะห์ข้อมูลหรือด้วย data visualization
    * ปัญหาที่สนใจมีความสำคัญอย่างไร?
    * ข้อคาดการณ์ของท่านจะนำไปสู่การแก้ไขปัญหาหรือตอบคำถามอย่างไร?
* สร้างตัวแบบทำนายโดยใช้ข้อมูลที่เลือกในการตอบปัญหาหรือคำถาม
    * prepare data
    * feature engineering
    * partition data (consider class if any)
    * handle imbalance data
    * build model
      * hyperparameter tuning
    * test model

#### ปัญหา/คำถามที่สนใจคืออะไร
...

#### ปัญหา/คำถามที่สนใจมีความสำคัญอย่างไร?
...

#### ข้อคาดการณ์ของท่านจะนำไปสู่การแก้ไขปัญหาหรือตอบคำถาม
1. ...
2. ...
3. ...
4. (Optional)
5. (Optional)

## Data Loading

### Mount drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

Mounted at /content/drive

### Load data

In [2]:
feature_path = "/content/drive/MyDrive/Big data/Walmart/features.csv"
stores_path = "/content/drive/MyDrive/Big data/Walmart/stores.csv"
train_path = "/content/drive/MyDrive/Big data/Walmart/train.csv"
test_path = "//content/drive/MyDrive/Big data/Walmart/test.csv"

df_ft = pd.read_csv(feature_path)
df_st = pd.read_csv(stores_path)
train = pd.read_csv(train_path)
test = pd.read_csv(test_path)

In [3]:
display(df_ft.head())

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,2010-02-05,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,2010-02-12,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,2010-02-19,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,2010-02-26,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,2010-03-05,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False

In [4]:
display(df_st.head())

   Store Type    Size
0      1    A  151315
1      2    A  202307
2      3    B   37392
3      4    A  205863
4      5    B   34875

In [5]:
display(train.head())

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  2010-02-05      24924.50      False
1      1     1  2010-02-12      46039.49       True
2      1     1  2010-02-19      41595.55      False
3      1     1  2010-02-26      19403.54      False
4      1     1  2010-03-05      21827.90      False

In [6]:
display(test.head())

   Store  Dept        Date  IsHoliday
0      1     1  2012-11-02      False
1      1     1  2012-11-09      False
2      1     1  2012-11-16      False
3      1     1  2012-11-23       True
4      1     1  2012-11-30      False

In [7]:
# Merge data if necessary
# merging 3 different sets
df = train.merge(df_ft, on=['Store', 'Date'], how='inner').merge(df_st, on=['Store'], how='inner')
df.head(5)

,Store,Dept,Date,Weekly_Sales,IsHoliday_x,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday_y,Type,Size
0,1,1,2010-02-05,24924.50,False,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False,A,151315
1,1,1,2010-02-12,46039.49,True,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True,A,151315
2,1,1,2010-02-19,41595.55,False,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False,A,151315
3,1,1,2010-02-26,19403.54,False,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False,A,151315
4,1,1,2010-03-05,21827.90,False,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False,A,151315

## Data Preparation

In [8]:
# Explore variables and check data quality

# Handle missing values, outliers, and noises

# Perform feature engineering (optional)

In [9]:
# Check if 'IsHoliday_x' and 'IsHoliday_y' columns match
print("Checking if IsHoliday_x and IsHoliday_y columns match:")
display((df['IsHoliday_x'] == df['IsHoliday_y']).all())

Checking if IsHoliday_x and IsHoliday_y columns match:

np.True_

### removing dublicated column : IsHoliday

In [10]:
df.drop(['IsHoliday_y'], axis=1,inplace=True) # removing dublicated column

In [11]:
df.rename(columns={'IsHoliday_x':'IsHoliday'},inplace=True) # rename the column

In [12]:
df.head() # last ready data set

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size
0,1,1,2010-02-05,24924.50,False,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,A,151315
1,1,1,2010-02-12,46039.49,True,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,A,151315
2,1,1,2010-02-19,41595.55,False,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,A,151315
3,1,1,2010-02-26,19403.54,False,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,A,151315
4,1,1,2010-03-05,21827.90,False,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,A,151315

In [13]:
df.shape

(421570, 16)

### Check Missing

In [14]:
df.isnull().sum()

Store                0
Dept                 0
Date                 0
Weekly_Sales         0
IsHoliday            0
Temperature          0
Fuel_Price           0
MarkDown1       270889
MarkDown2       310322
MarkDown3       284479
MarkDown4       286603
MarkDown5       270138
CPI                  0
Unemployment         0
Type                 0
Size                 0
dtype: int64

### เติม 0 ใน Markdown

In [15]:
markdown_cols = ['MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5']
df[markdown_cols] = df[markdown_cols].fillna(0)

In [16]:
df.isnull().sum()

Store           0
Dept            0
Date            0
Weekly_Sales    0
IsHoliday       0
Temperature     0
Fuel_Price      0
MarkDown1       0
MarkDown2       0
MarkDown3       0
MarkDown4       0
MarkDown5       0
CPI             0
Unemployment    0
Type            0
Size            0
dtype: int64

In [17]:
df.head()

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size
0,1,1,2010-02-05,24924.50,False,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,8.106,A,151315
1,1,1,2010-02-12,46039.49,True,38.51,2.548,0.0,0.0,0.0,0.0,0.0,211.242170,8.106,A,151315
2,1,1,2010-02-19,41595.55,False,39.93,2.514,0.0,0.0,0.0,0.0,0.0,211.289143,8.106,A,151315
3,1,1,2010-02-26,19403.54,False,46.63,2.561,0.0,0.0,0.0,0.0,0.0,211.319643,8.106,A,151315
4,1,1,2010-03-05,21827.90,False,46.50,2.625,0.0,0.0,0.0,0.0,0.0,211.350143,8.106,A,151315

### Weekly_Sales <=0

In [18]:
df.loc[df['Weekly_Sales']<=0]

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size
846,1,6,2012-08-10,-139.65,False,85.05,3.494,11436.22,245.0,6.85,6964.26,4836.22,221.958433,6.908,A,151315
2384,1,18,2012-05-04,-1.27,False,75.55,3.749,21290.13,0.0,69.89,4977.35,3261.04,221.671800,7.143,A,151315
6048,1,47,2010-02-19,-863.00,False,39.93,2.514,0.00,0.0,0.00,0.00,0.00,211.289143,8.106,A,151315
6049,1,47,2010-03-12,-698.00,False,57.79,2.667,0.00,0.0,0.00,0.00,0.00,211.380643,8.106,A,151315
6051,1,47,2010-10-08,-58.00,False,63.93,2.633,0.00,0.0,0.00,0.00,0.00,211.746754,7.838,A,151315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419597,45,80,2010-02-12,-0.43,True,27.73,2.773,0.00,0.0,0.00,0.00,0.00,181.982317,8.992,B,118221
419598,45,80,2010-02-19,-0.27,False,31.27,2.745,0.00,0.0,0.00,0.00,0.00,182.034782,8.992,B,118221
419603,45,80,2010-04-16,-1.61,False,54.28,2.899,0.00,0.0,0.00,0.00,0.00,181.692477,8.899,B,118221
419614,45,80,2010-07-02,-0.27,False,76.61,2.815,0.00,0.0,0.00,0.00,0.00,182.318780,8.743,B,118221
419640,45,80,2011-02-11,-0.24,True,30.30,3.239,0.00,0.0,0.00,0.00,0.00,183.701613,8.549,B,118221

### เนื่องจาก 1358 แถว คิดเป็น 0.3%จากทั้งหมด จึงเลือกลบข้อมูล

In [19]:
df = df.loc[df['Weekly_Sales'] > 0]

In [20]:
df.shape # new data shape

(420212, 16)

### Date

In [21]:
# Use pd.concat to combine head and tail
display(pd.concat([df['Date'].head(5), df['Date'].tail(5)]))

0         2010-02-05
1         2010-02-12
2         2010-02-19
3         2010-02-26
4         2010-03-05
421565    2012-09-28
421566    2012-10-05
421567    2012-10-12
421568    2012-10-19
421569    2012-10-26
Name: Date, dtype: object

### Changing Date to Datetime and Creating New Columns

In [22]:
df["Date"] = pd.to_datetime(df["Date"]) # convert to datetime
df['week'] =df['Date'].dt.isocalendar().week.astype(int)
df['month'] =df['Date'].dt.month
df['year'] =df['Date'].dt.year

In [23]:
df

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Type,Size,week,month,year
0,1,1,2010-02-05,24924.50,False,42.31,2.572,0.00,0.00,0.00,0.00,0.00,211.096358,8.106,A,151315,5,2,2010
1,1,1,2010-02-12,46039.49,True,38.51,2.548,0.00,0.00,0.00,0.00,0.00,211.242170,8.106,A,151315,6,2,2010
2,1,1,2010-02-19,41595.55,False,39.93,2.514,0.00,0.00,0.00,0.00,0.00,211.289143,8.106,A,151315,7,2,2010
3,1,1,2010-02-26,19403.54,False,46.63,2.561,0.00,0.00,0.00,0.00,0.00,211.319643,8.106,A,151315,8,2,2010
4,1,1,2010-03-05,21827.90,False,46.50,2.625,0.00,0.00,0.00,0.00,0.00,211.350143,8.106,A,151315,9,3,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421565,45,98,2012-09-28,508.37,False,64.88,3.997,4556.61,20.64,1.50,1601.01,3288.25,192.013558,8.684,B,118221,39,9,2012
421566,45,98,2012-10-05,628.10,False,64.89,3.985,5046.74,0.00,18.82,2253.43,2340.01,192.170412,8.667,B,118221,40,10,2012
421567,45,98,2012-10-12,1061.02,False,54.47,4.000,1956.28,0.00,7.89,599.32,3990.54,192.327265,8.667,B,118221,41,10,2012
421568,45,98,2012-10-19,760.01,False,56.47,3.969,2004.02,0.00,3.18,437.73,1537.49,192.330854,8.667,B,118221,42,10,2012
421569,45,98,2012-10-26,1076.80,False,58.85,3.882,4018.91,58.08,100.00,211.94,858.33,192.308899,8.667,B,118221,43,10,2012

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
# Specify the path to save the CSV file in Google Drive
output_path = "/content/drive/MyDrive/processed_walmart_train_data.csv"

# Save the dataframe to CSV
try:
    df.to_csv(output_path, index=False)
    print(f"DataFrame saved successfully to {output_path}")
except Exception as e:
    print(f"Error saving DataFrame: {e}")
    print("Please ensure Google Drive is mounted correctly and you have write permissions for the specified path.")

DataFrame saved successfully to /content/drive/MyDrive/processed_walmart_train_data.csv

## Explore Data

In [26]:
# Descriptive statistics

# Data visualization
# Target variable analysis: examine how each feature correlates with or impacts the target/interested variable

## Data Modeling

In [27]:
# Partition data

# Handle imbalance data (optional)

# Model selection and tuning

# Evaluate models

-----------------
# เสร็จแล้ววววว 🥳

สิ่งที่ต้องแนบส่ง:
* Notebook File (ตัวอย่าง "filename.ipynb") หรือ Link to Google Colab / GitHub ซึ่งมีผลลัพธ์จากการรันโค้ดแสดงทั้งหมด
* Slides สำหรับการนำเสนอ **10** นาที ซึ่งประกอบไปด้วย
    * Data Description: อธิบายข้อมูลที่ใช้
    * Data Preparation: การเตรียมข้อมูลก่อนวิเคราะห์
    * Motivation: ปัญหาหรือคำถามที่ตั้ง ทำไมถึงสนใจที่จะทำงานในเรื่องนี้
    * Communicating Results (with figure, table, etc.): ผลที่ได้จากการศึกษา โดยระบุแนวทางที่ใช้ที่ทำให้เกิดผลลัพธ์ดังกล่าวด้วย
        โดยไม่ต้องนำเสนอ source code ผลประกอบด้วย 2 ส่วนสำคัญ จาก
        * Conjectures >= 3 ข้อ
        * Machine learning models
    * Conclusion: สรุปผลที่ได้จากการวิเคราะห์ข้อมูล
** Note: แต่ละกลุ่มส่งแต่ละไฟล์ครั้งเดียว **
---------------------

1. การเล่าเรื่องราวจากข้อมูล (Tell Story About Data)

อธิบายลักษณะของข้อมูลและทำความเข้าใจ (Data Description and Understanding)

ชุดข้อมูลนี้มีวัตถุประสงค์เพื่อทำนาย Weekly_Sales (ยอดขายรายสัปดาห์) ซึ่งเป็น ตัวแปรเป้าหมายเชิงปริมาณ (Continuous Numerical Target) ดังนั้นตัวแบบทำนายที่เราจะสร้างจะเป็น ตัวแบบการถดถอย (Regression Model)

ข้อมูลประกอบด้วยตารางหลัก 4 ตารางที่ต้องนำมารวมกัน (Merge):

1. train.csv (ข้อมูลการฝึกสอน):

- Store, Dept, Date: รหัสร้าน, รหัสแผนก, วันที่ (ใช้รวมข้อมูล)

- Weekly_Sales: ตัวแปรเป้าหมาย (ยอดขาย)

- IsHoliday: เป็นวันหยุดหรือไม่ (ตัวแปรคุณลักษณะ)

2. test.csv (ข้อมูลการทดสอบ/ทำนาย): มีโครงสร้างคล้าย train.csv แต่ ไม่มี คอลัมน์ Weekly_Sales

3.stores.csv (ข้อมูลร้านค้า):

- Store: รหัสร้านค้า

- Type: ประเภทของร้านค้า (A, B, C)

- Size: ขนาดพื้นที่ของร้านค้า (ตัวแปรคุณลักษณะ)

4.features.csv (ข้อมูลคุณลักษณะภายนอก):

- Store, Date: รหัสร้าน, วันที่ (ใช้รวมข้อมูล)

- Temperature: อุณหภูมิโดยเฉลี่ยของภูมิภาค

- Fuel_Price: ราคาน้ำมัน

- CPI: ดัชนีราคาผู้บริโภค

- Unemployment: อัตราการว่างงาน

- MarkDown1-5: ข้อมูลโปรโมชั่นลดราคา (มีค่าว่างจำนวนมาก)

- IsHoliday: เป็นวันหยุดหรือไม่ (ใช้ยืนยัน)

ทำความเข้าใจด้วยสถิติ (Statistical Understanding)

- Weekly_Sales: มีค่าเฉลี่ย (Mean) และค่ามัธยฐาน (Median) ที่ค่อนข้างแตกต่างกัน (Skewed Distribution) และมีค่า Outliers (ยอดขายสูงหรือต่ำผิดปกติ)

- IsHoliday: ยอดขายในวันหยุด (TRUE) อาจมีค่าเฉลี่ยสูงกว่าวันปกติ (FALSE) อย่างมีนัยสำคัญ

- Store Size & Type: ขนาดร้านค้า Size และประเภท Type น่าจะมีความสัมพันธ์เชิงบวกกับ Weekly_Sales (ร้านใหญ่ขายดีกว่า)

- MarkDowns: โปรโมชั่น MarkDown1-5 มีค่าว่างมาก ซึ่งแสดงว่าโปรโมชั่นเหล่านี้ไม่ได้มีตลอดเวลา หรืออาจเป็นค่าศูนย์

นำเสนอด้วยแผนภาพ (Data Visualization)

แผนภาพที่ 1: การกระจายตัวของยอดขาย

- Histogram of Weekly_Sales: แสดงให้เห็นว่ายอดขายส่วนใหญ่กระจุกตัวอยู่ที่ค่าต่ำๆ แต่มีหางยาวไปทางขวา (Right-skewed) ซึ่งยืนยันการมี Outliers ที่สูงมาก

แผนภาพที่ 2: ยอดขายตามประเภทและขนาดร้าน

- Box Plot: Weekly_Sales vs Store_Type: แสดงให้เห็นว่าร้านค้าประเภท Type A อาจมียอดขายเฉลี่ยสูงสุด ตามด้วย Type B และ Type C ซึ่งสอดคล้องกับขนาดร้านค้า

- Scatter Plot: Weekly_Sales vs Size: แสดงความสัมพันธ์เชิงบวกระหว่างขนาดร้านค้ากับยอดขาย

แผนภาพที่ 3: ผลกระทบของวันหยุด

- Bar Chart/Box Plot: Weekly_Sales vs IsHoliday: แสดงความแตกต่างของยอดขายในสัปดาห์ที่เป็นวันหยุด (เช่น Black Friday/Christmas) เทียบกับสัปดาห์ปกติ

2. การตั้งปัญหา, การคาดการณ์, และการวิเคราะห์

ปัญหา/คำถามเชิงองค์กรหรือธุรกิจที่สนใจ

"ปัจจัยเศรษฐกิจมหภาค (Macroeconomic Factors) และกิจกรรมส่งเสริมการขาย (MarkDowns) มีอิทธิพลต่อยอดขายรายสัปดาห์อย่างไร และเราจะสร้างตัวแบบที่แม่นยำเพื่อพยากรณ์ยอดขายเพื่อเพิ่มประสิทธิภาพการบริหารจัดการสินค้าคงคลัง (Inventory) ได้อย่างไร?"

ความสำคัญของปัญหา

การพยากรณ์ยอดขายรายสัปดาห์ที่แม่นยำเป็นหัวใจสำคัญของการดำเนินงานร้านค้าปลีก:

- การบริหารสินค้าคงคลัง (Inventory Management): ช่วยลดต้นทุนการเก็บรักษาสินค้า (Holding Costs) และป้องกันการขาดแคลนสินค้า (Stockouts)

- การจัดสรรบุคลากร: วางแผนกำลังคนให้เพียงพอในช่วงยอดขายสูง

- การวางแผนกลยุทธ์การตลาด: เข้าใจว่าโปรโมชั่น (MarkDowns) ใดมีประสิทธิภาพสูงสุด

ข้อคาดการณ์ (Conjectures) 3 ข้อ

1. ข้อคาดการณ์ที่ 1 (วันหยุด): ยอดขายรายสัปดาห์ในช่วงสัปดาห์ที่เป็นวันหยุด (โดยเฉพาะวันหยุดใหญ่) จะมีค่าเฉลี่ย สูงกว่า สัปดาห์ปกติอย่างมีนัยสำคัญ

2. ข้อคาดการณ์ที่ 2 (CPI/Unemployment): ตัวชี้วัดทางเศรษฐกิจ CPI (เงินเฟ้อ) และ Unemployment (ว่างงาน) จะมีความสัมพันธ์ เชิงลบ กับยอดขาย (เมื่อเศรษฐกิจไม่ดี ยอดขายจะลดลง)

3. ข้อคาดการณ์ที่ 3 (MarkDowns): โปรโมชั่นลดราคา MarkDowns จะมีความสัมพันธ์ เชิงบวก กับยอดขาย แต่ MarkDown บางประเภทจะมีประสิทธิภาพสูงกว่าประเภทอื่น

![image.png]()

ความสำคัญของการแก้ไขปัญหา & การนำไปสู่การแก้ไข

- ปัญหาที่สนใจมีความสำคัญ: การเข้าใจว่าปัจจัยใดมีผลต่อยอดขาย (เช่น วันหยุด, โปรโมชั่น) ช่วยให้บริษัท ปรับกลยุทธ์ด้านราคาและสินค้า ในสัปดาห์ที่สำคัญเพื่อ เพิ่มกำไรสูงสุด

- ข้อคาดการณ์จะนำไปสู่การแก้ไขปัญหา:

  - การยืนยันว่า วันหยุด มีผลสูง (ข้อ 1) จะนำไปสู่การ สต็อกสินค้าให้มาก และ จัดตารางพนักงาน ให้เพียงพอในช่วงเวลานั้น

  - การยืนยันว่า MarkDowns มีผล (ข้อ 3) จะนำไปสู่การ จัดสรรงบประมาณโปรโมชั่น ไปที่ MarkDown ประเภทที่มีประสิทธิภาพสูงสุด (MarkDown1/4) และวางแผนสินค้าที่จะลดราคาให้แม่นยำตามการพยากรณ์

# random forest

# การทำ Random Forest Regression สำหรับทำนายยอดขายรายสัปดาห์

## วัตถุประสงค์ของโครงการ และเหตุผลที่เลือกใช้ Random Forest Regressor

### วัตถุประสงค์
มีวัตถุประสงค์หลักคือการ **สร้างตัวแบบ (Model)** ที่สามารถ **ทำนายยอดขายรายสัปดาห์ (`Weekly_Sales`)** ของร้านค้าและแผนกต่างๆ ของ Walmart ได้อย่างแม่นยำ โดยใช้ข้อมูลในอดีตและปัจจัยต่างๆ ที่เกี่ยวข้อง เช่น สภาพเศรษฐกิจ โปรโมชั่น และคุณลักษณะของร้านค้า

การทำนายยอดขายนี้มีประโยชน์อย่างยิ่งในการช่วยให้ Walmart:
*   **วางแผนการจัดการสินค้าคงคลัง** ได้อย่างมีประสิทธิภาพ
*   **จัดตารางการทำงานของพนักงาน** ให้เหมาะสม
*   **วางแผนกลยุทธ์การตลาดและโปรโมชั่น** ได้ตรงจุด
*   **คาดการณ์และประเมินผลประกอบการ** ในอนาคต

### เหตุผลที่เลือกใช้ Random Forest Regressor

เราตัดสินใจเลือกใช้ Random Forest Regressor ในการทำนายยอดขายรายสัปดาห์จากหลายเหตุผล:

1.  **ความแม่นยำ:** Random Forest มักให้ผลการทำนายที่ค่อนข้างแม่นยำสำหรับงาน Regression โดยเฉพาะกับข้อมูลที่มีความสัมพันธ์ที่ซับซ้อน
2.  **จัดการกับความสัมพันธ์ที่ไม่เป็นเชิงเส้น:** ตัวแบบนี้สามารถจับรูปแบบความสัมพันธ์ระหว่างคุณลักษณะต่างๆ กับยอดขายที่ไม่ใช่เส้นตรงได้ดี ซึ่งเป็นเรื่องปกติในข้อมูลยอดขายจริง
3.  **ความทนทานต่อ Outliers:** Random Forest ไม่ค่อยอ่อนไหวต่อค่าผิดปกติ (Outliers) ในข้อมูลมากนัก เมื่อเทียบกับโมเดลประเภทอื่นๆ
4.  **จัดการข้อมูลได้หลากหลาย:** สามารถทำงานได้ดีกับคุณลักษณะทั้งที่เป็นตัวเลขและหมวดหมู่ (เมื่อแปลงแล้ว) โดยไม่ต้องปรับสเกลข้อมูล
5.  **บอกความสำคัญของ Feature:** ตัวแบบสามารถบอกได้ว่าคุณลักษณะใดมีความสำคัญที่สุดในการทำนาย ซึ่งช่วยให้เราเข้าใจปัจจัยขับเคลื่อนยอดขายได้ดียิ่งขึ้น
6.  **ลดปัญหา Overfitting:** การใช้เทคนิค Ensemble (รวมหลายต้นไม้) ช่วยลดความเสี่ยงที่โมเดลจะเรียนรู้ข้อมูลฝึกสอนมากเกินไปจนทำนายข้อมูลใหม่ได้ไม่ดี

## การแสดงความสัมพันธ์ที่อาจบ่งชี้ถึงความซับซ้อนในข้อมูล

เราจะสร้างกราฟเพื่อสำรวจความสัมพันธ์ระหว่างคุณลักษณะบางตัวกับยอดขายรายสัปดาห์ (`Weekly_Sales`) ซึ่งอาจแสดงให้เห็นถึงรูปแบบที่ไม่เป็นเชิงเส้นหรือความสัมพันธ์ที่ซับซ้อนครับ

### ขั้นตอนที่ 1: นำเข้าไลบรารีที่จำเป็น (Import Libraries)

In [28]:
# นำเข้าไลบรารีสำหรับการจัดการข้อมูล, การสร้างกราฟ, และโมเดล Machine Learning
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns # เพิ่ม seaborn เพื่อช่วยในการสร้างกราฟที่สวยงามขึ้น

from sklearn.model_selection import train_test_split # สำหรับแบ่งข้อมูล
from sklearn.ensemble import RandomForestRegressor # โมเดล Random Forest สำหรับ Regression
from sklearn.metrics import mean_absolute_error, mean_squared_error # Metric สำหรับประเมินผล

### ขั้นตอนที่ 2: โหลดและรวมข้อมูล (Load and Merge Data)

เราจะโหลดไฟล์ข้อมูล `features.csv`, `stores.csv`, `train.csv` และ `test.csv` จาก Google Drive ของคุณ จากนั้นนำข้อมูลที่เกี่ยวข้องมารวมกันเพื่อใช้ในการวิเคราะห์และสร้างโมเดลครับ

**หมายเหตุ:** ตรวจสอบให้แน่ใจว่าได้ Mount Google Drive และพาธไฟล์ถูกต้อง

In [29]:
# Paths to the data files (adjust if your paths are different)
feature_path = "/content/drive/MyDrive/Big data/Walmart/features.csv"
stores_path = "/content/drive/MyDrive/Big data/Walmart/stores.csv"
train_path = "/content/drive/MyDrive/Big data/Walmart/train.csv"
test_path = "/content/drive/MyDrive/Big data/Walmart/test.csv"

# Use a try-except block to catch FileNotFoundError and provide user feedback
try:
    # Load the data into pandas DataFrames
    df_ft = pd.read_csv(feature_path)
    df_st = pd.read_csv(stores_path)
    train = pd.read_csv(train_path)
    test = pd.read_csv(test_path)

    print("ไฟล์ features.csv โหลดสำเร็จ (5 แถวแรก):")
    display(df_ft.head())

    print("\nไฟล์ stores.csv โหลดสำเร็จ (5 แถวแรก):")
    display(df_st.head())

    print("\nไฟล์ train.csv โหลดสำเร็จ (5 แถวแรก):")
    display(train.head())

    print("\nไฟล์ test.csv โหลดสำเร็จ (5 แถวแรก):")
    display(test.head())

    print("\n====== สรุปผลการโหลดไฟล์: โหลดสำเร็จทุกไฟล์ ======")

except FileNotFoundError as e:
    print(f"\nข้อผิดพลาด: ไม่พบไฟล์ข้อมูล! {e}")
    print("โปรดตรวจสอบว่า:")
    print("1. คุณได้ Mount Google Drive อย่างถูกต้องแล้ว (ดู Cell ที่ Mount Drive)")
    print(f"2. พาธไฟล์ {e.filename} ถูกต้องและไฟล์อยู่ในโฟลเดอร์ที่ระบุจริง")
    print("เมื่อแก้ไขแล้ว โปรดรัน Cell นี้อีกครั้ง")
    # Set dataframes to None or empty to avoid NameError in subsequent cells if user proceeds
    df_ft, df_st, train, test = None, None, None, None

except Exception as e:
    print(f"\nเกิดข้อผิดพลาดที่ไม่คาดคิดในการโหลดไฟล์: {e}")
    # Set dataframes to None or empty
    df_ft, df_st, train, test = None, None, None, None

ไฟล์ features.csv โหลดสำเร็จ (5 แถวแรก):

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,2010-02-05,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,2010-02-12,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,2010-02-19,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,2010-02-26,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,2010-03-05,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False

ไฟล์ stores.csv โหลดสำเร็จ (5 แถวแรก):

   Store Type    Size
0      1    A  151315
1      2    A  202307
2      3    B   37392
3      4    A  205863
4      5    B   34875

ไฟล์ train.csv โหลดสำเร็จ (5 แถวแรก):

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  2010-02-05      24924.50      False
1      1     1  2010-02-12      46039.49       True
2      1     1  2010-02-19      41595.55      False
3      1     1  2010-02-26      19403.54      False
4      1     1  2010-03-05      21827.90      False

ไฟล์ test.csv โหลดสำเร็จ (5 แถวแรก):

   Store  Dept        Date  IsHoliday
0      1     1  2012-11-02      False
1      1     1  2012-11-09      False
2      1     1  2012-11-16      False
3      1     1  2012-11-23       True
4      1     1  2012-11-30      False

====== สรุปผลการโหลดไฟล์: โหลดสำเร็จทุกไฟล์ ======

จากนั้น เราจะรวมข้อมูล `train` เข้ากับ `df_ft` (features) โดยใช้คอลัมน์ `Store` และ `Date` เป็นหลัก และรวมผลลัพธ์เข้ากับ `df_st` (stores) โดยใช้คอลัมน์ `Store`

### ขั้นตอนที่ 3: การเตรียมข้อมูล (Data Preparation)

สำรวจข้อมูลเบื้องต้นเพื่อทำความเข้าใจโครงสร้างข้อมูล, ประเภทข้อมูล, และค่าที่หายไป

In [30]:
# Check data types and missing values
print("ข้อมูลเบื้องต้น (df.info()):")
df.info()

ข้อมูลเบื้องต้น (df.info()):
<class 'pandas.core.frame.DataFrame'>
Index: 420212 entries, 0 to 421569
Data columns (total 19 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         420212 non-null  int64
 1   Dept          420212 non-null  int64
 2   Date          420212 non-null  datetime64[ns]
 3   Weekly_Sales  420212 non-null  float64
 4   IsHoliday     420212 non-null  bool
 5   Temperature   420212 non-null  float64
 6   Fuel_Price    420212 non-null  float64
 7   MarkDown1     420212 non-null  float64
 8   MarkDown2     420212 non-null  float64
 9   MarkDown3     420212 non-null  float64
 10  MarkDown4     420212 non-null  float64
 11  MarkDown5     420212 non-null  float64
 12  CPI           420212 non-null  float64
 13  Unemployment  420212 non-null  float64
 14  Type          420212 non-null  object
 15  Size          420212 non-null  int64
 16  week          420212 non-null  int64
 17  month         420212 non-null  int32
 18  year          420212 non-null  int32
dtypes: bool(1), datetime64[ns](1), float64(10), int32(2), int64(4), object(1)
memory usage: 58.1+ MB

In [31]:
# Get descriptive statistics
print("\nข้อมูลสถิติสรุป (df.describe()):")
display(df.describe())

ข้อมูลสถิติสรุป (df.describe()):

,Store,Dept,Date,Weekly_Sales,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,Size,week,month,year
count,420212.000000,420212.000000,420212,420212.000000,420212.000000,420212.000000,420212.000000,420212.000000,420212.000000,420212.000000,420212.000000,420212.000000,420212.000000,420212.000000,420212.000000,420212.000000,420212.000000
mean,22.195611,44.241309,2011-06-18 07:35:12.682169600,16033.114591,60.090599,3.360890,2590.323565,878.905242,468.845949,1083.534361,1662.805002,171.212496,7.960000,136749.732787,25.828408,6.449866,2010.968454
min,1.000000,1.000000,2010-02-05 00:00:00,0.010000,-2.060000,2.472000,0.000000,-265.760000,-29.100000,0.000000,0.000000,126.064000,3.879000,34875.000000,1.000000,1.000000,2010.000000
25%,11.000000,18.000000,2010-10-08 00:00:00,2120.130000,46.680000,2.933000,0.000000,0.000000,0.000000,0.000000,0.000000,132.022667,6.891000,93638.000000,14.000000,4.000000,2010.000000
50%,22.000000,37.000000,2011-06-17 00:00:00,7661.700000,62.090000,3.452000,0.000000,0.000000,0.000000,0.000000,0.000000,182.350989,7.866000,140167.000000,26.000000,6.000000,2011.000000
75%,33.000000,74.000000,2012-02-24 00:00:00,20271.265000,74.280000,3.738000,2809.050000,2.400000,4.540000,425.290000,2168.040000,212.445487,8.567000,202505.000000,38.000000,9.000000,2012.000000
max,45.000000,99.000000,2012-10-26 00:00:00,693099.360000,100.140000,4.468000,88646.760000,104519.540000,141630.610000,67474.850000,108519.280000,227.232807,14.313000,219622.000000,52.000000,12.000000,2012.000000
std,12.787236,30.508819,NaN,22729.492116,18.447857,0.458519,6053.415601,5076.928566,5534.069859,3896.068938,4206.209357,39.162445,1.863879,60993.084568,14.152489,3.243397,0.796898

จัดการกับค่าว่างในคอลัมน์ MarkDowns โดยเติมด้วย 0 เนื่องจากค่าว่างน่าจะหมายถึงไม่มีโปรโมชั่นในช่วงเวลานั้น

In [32]:
# Handle missing values in MarkDown columns
markdown_cols = ['MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5']
df[markdown_cols] = df[markdown_cols].fillna(0)

print("\nตรวจสอบค่าว่างหลังเติม 0 ในคอลัมน์ MarkDowns:")
print(df[markdown_cols].isnull().sum())

ตรวจสอบค่าว่างหลังเติม 0 ในคอลัมน์ MarkDowns:
MarkDown1    0
MarkDown2    0
MarkDown3    0
MarkDown4    0
MarkDown5    0
dtype: int64

ลบแถวที่ Weekly_Sales น้อยกว่าหรือเท่ากับ 0 เนื่องจากน่าจะเป็นข้อมูลที่ไม่ถูกต้องหรือไม่เกี่ยวข้อง

In [33]:
# Remove rows with Weekly_Sales <= 0
initial_rows = df.shape[0]
df = df.loc[df['Weekly_Sales'] > 0]
rows_removed = initial_rows - df.shape[0]

print(f"\nจำนวนแถวที่ถูกลบเนื่องจาก Weekly_Sales <= 0: {rows_removed}")
print(f"จำนวนแถวที่เหลือ: {df.shape[0]}")

จำนวนแถวที่ถูกลบเนื่องจาก Weekly_Sales <= 0: 0
จำนวนแถวที่เหลือ: 420212

สร้างคุณลักษณะใหม่จากข้อมูลวันที่ เพื่อจับรูปแบบตามฤดูกาลและเวลา

In [34]:
# Create date-related features
df["Date"] = pd.to_datetime(df["Date"])
df['week'] = df['Date'].dt.isocalendar().week.astype(int)
df['month'] = df['Date'].dt.month
df['year'] = df['Date'].dt.year
df['dayofweek'] = df['Date'].dt.dayofweek
df['quarter'] = df['Date'].dt.quarter

print("\nข้อมูลพร้อม Feature จากวันที่ (5 แถวแรก):")
display(df.head())

ข้อมูลพร้อม Feature จากวันที่ (5 แถวแรก):

,Store,Dept,Date,Weekly_Sales,IsHoliday,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,...,MarkDown5,CPI,Unemployment,Type,Size,week,month,year,dayofweek,quarter
0,1,1,2010-02-05,24924.50,False,42.31,2.572,0.0,0.0,0.0,...,0.0,211.096358,8.106,A,151315,5,2,2010,4,1
1,1,1,2010-02-12,46039.49,True,38.51,2.548,0.0,0.0,0.0,...,0.0,211.242170,8.106,A,151315,6,2,2010,4,1
2,1,1,2010-02-19,41595.55,False,39.93,2.514,0.0,0.0,0.0,...,0.0,211.289143,8.106,A,151315,7,2,2010,4,1
3,1,1,2010-02-26,19403.54,False,46.63,2.561,0.0,0.0,0.0,...,0.0,211.319643,8.106,A,151315,8,2,2010,4,1
4,1,1,2010-03-05,21827.90,False,46.50,2.625,0.0,0.0,0.0,...,0.0,211.350143,8.106,A,151315,9,3,2010,4,1

แปลงข้อมูลหมวดหมู่ (Categorical Features) เช่น 'Type' และ 'IsHoliday_x' ให้เป็นตัวเลขด้วย One-Hot Encoding เพื่อให้โมเดลนำไปใช้ได้

In [35]:
import pandas as pd # ตรวจสอบว่า import pandas แล้ว

# --- แก้ไขส่วนของ 'Type' ---
# Handle the 'Type' column
if 'Type' in df.columns:
    # เพิ่ม dtype=int เพื่อให้ผลลัพธ์เป็น 0/1 แทน True/False
    df = pd.get_dummies(df, columns=['Type'], prefix='Type', dtype=int)
    print("One-Hot Encoded 'Type' column (as 0/1).")
else:
    print("Warning: 'Type' column not found for encoding.")


# Now, handle the 'IsHoliday' column.
# (ส่วนนี้โค้ดเดิมของคุณจัดการดีแล้ว แต่เราจะใช้ dtype=int เพื่อให้สอดคล้องกัน)
if 'IsHoliday_y' in df.columns:
    df = df.drop('IsHoliday_y', axis=1)
    print("Dropped 'IsHoliday_y' column.")

# --- แก้ไขส่วนของ 'IsHoliday_x' ---
if 'IsHoliday_x' in df.columns:
    # เพิ่ม dtype=int และเราไม่จำเป็นต้องใช้ .astype(int) อีกต่อไป
    df = pd.get_dummies(df, columns=['IsHoliday_x'], prefix='IsHoliday', dtype=int)
    print("One-Hot Encoded 'IsHoliday_x' column (as 0/1).")

    # บรรทัด .astype(int) ด้านล่างนี้ไม่จำเป็นแล้ว เพราะ dtype=int จัดการให้แล้ว
    # if 'IsHoliday_False' in df.columns:
    #     df['IsHoliday_False'] = df['IsHoliday_False'].astype(int)
    # if 'IsHoliday_True' in df.columns:
    #     df['IsHoliday_True'] = df['IsHoliday_True'].astype(int)

# --- แก้ไขส่วนของ 'IsHoliday' (Fallback) ---
elif 'IsHoliday' in df.columns:
    # เพิ่ม dtype=int ที่นี่ด้วย
    df = pd.get_dummies(df, columns=['IsHoliday'], prefix='IsHoliday', dtype=int)
    print("One-Hot Encoded 'IsHoliday' column (as 0/1).")

    # บรรทัด .astype(int) ด้านล่างนี้ไม่จำเป็นแล้ว
    # if 'IsHoliday_False' in df.columns:
    #     df['IsHoliday_False'] = df['IsHoliday_False'].astype(int)
    # if 'IsHoliday_True' in df.columns:
    #     df['IsHoliday_True'] = df['IsHoliday_True'].astype(int)

else:
    print("Warning: Neither 'IsHoliday_x' nor 'IsHoliday' column found for encoding.")


print("\nข้อมูลหลัง One-Hot Encoding (5 แถวแรก):")
display(df.head())

One-Hot Encoded 'Type' column (as 0/1).
One-Hot Encoded 'IsHoliday' column (as 0/1).

ข้อมูลหลัง One-Hot Encoding (5 แถวแรก):

,Store,Dept,Date,Weekly_Sales,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,...,week,month,year,dayofweek,quarter,Type_A,Type_B,Type_C,IsHoliday_False,IsHoliday_True
0,1,1,2010-02-05,24924.50,42.31,2.572,0.0,0.0,0.0,0.0,...,5,2,2010,4,1,1,0,0,1,0
1,1,1,2010-02-12,46039.49,38.51,2.548,0.0,0.0,0.0,0.0,...,6,2,2010,4,1,1,0,0,0,1
2,1,1,2010-02-19,41595.55,39.93,2.514,0.0,0.0,0.0,0.0,...,7,2,2010,4,1,1,0,0,1,0
3,1,1,2010-02-26,19403.54,46.63,2.561,0.0,0.0,0.0,0.0,...,8,2,2010,4,1,1,0,0,1,0
4,1,1,2010-03-05,21827.90,46.50,2.625,0.0,0.0,0.0,0.0,...,9,3,2010,4,1,1,0,0,1,0

ก่อนทำ One-Hot Encoding คอลัมน์ IsHoliday_x มีค่าอยู่ 2 แบบคือ True (เป็นวันหยุด) หรือ False (ไม่เป็นวันหยุด) เราต้องการแปลงข้อมูล 2 แบบนี้ให้เป็นตัวเลขครับ
One-Hot Encoding ทำแบบนี้:
สร้างคอลัมน์ใหม่ขึ้นมา 2 คอลัมน์ คือ IsHoliday_False และ IsHoliday_True
สำหรับแต่ละแถวข้อมูล:
* ถ้าค่าเดิมใน IsHoliday_x เป็น False (ไม่เป็นวันหยุด):

คอลัมน์ IsHoliday_False จะมีค่าเป็น 1

คอลัมน์ IsHoliday_True จะมีค่าเป็น 0
* ถ้าค่าเดิมใน IsHoliday_x เป็น True (เป็นวันหยุด):

คอลัมน์ IsHoliday_False จะมีค่าเป็น 0

คอลัมน์ IsHoliday_True จะมีค่าเป็น 1

ดังนั้น:

* ค่า 1 ในคอลัมน์ใดคอลัมน์หนึ่ง (เช่น IsHoliday_True = 1) หมายถึงว่าแถวข้อมูลนั้น "ตรงกับ" ประเภทที่คอลัมน์นั้นสื่อถึง
* ค่า 0 ในคอลัมน์ใดคอลัมน์หนึ่ง (เช่น IsHoliday_True = 0) หมายถึงว่าแถวข้อมูลนั้น "ไม่ตรงกับ" ประเภทที่คอลัมน์นั้น

คอลัมน์ที่สร้างขึ้นและความหมาย:

1. week: คอลัมน์นี้เก็บ หมายเลขสัปดาห์ ของปีครับ ตัวอย่างเช่น สัปดาห์แรกของปีจะเป็นสัปดาห์ที่ 1, สัปดาห์ที่สองจะเป็นสัปดาห์ที่ 2 ไปเรื่อยๆ จนถึงสัปดาห์สุดท้ายของปี (อาจจะเป็นสัปดาห์ที่ 52 หรือ 53 ขึ้นอยู่กับการนับสัปดาห์แบบ ISO)
เหตุผล: ยอดขายมักมีรูปแบบตามฤดูกาล เช่น อาจจะสูงขึ้นในช่วงเทศกาลต่างๆ ที่อยู่ในสัปดาห์เฉพาะ การรู้หมายเลขสัปดาห์ช่วยให้โมเดลเรียนรู้รูปแบบเหล่านี้ได้
2. month: คอลัมน์นี้เก็บ หมายเลขเดือน ของปี 1 คือ มกราคม, 2 คือ กุมภาพันธ์, ... 12 คือ ธันวาคม
เหตุผล: คล้ายกับสัปดาห์ ยอดขายมีแนวโน้มตามเดือน เช่น อาจจะสูงขึ้นในช่วงปลายปี (เดือน 11, 12) เนื่องจากเทศกาลต่างๆ การรู้เดือนช่วยให้โมเดลจับแนวโน้มตามเดือนได้
3. year: คอลัมน์นี้เก็บ ปี ครับ เช่น 2010, 2011, 2012
เหตุผล: ช่วยให้โมเดลเรียนรู้แนวโน้มยอดขายในแต่ละปี ซึ่งอาจแตกต่างกันไปเนื่องจากปัจจัยทางเศรษฐกิจที่เปลี่ยนแปลงไปในแต่ละปี
4. dayofweek: คอลัมน์นี้เก็บ หมายเลขวันในสัปดาห์ โดยทั่วไป วันจันทร์คือ 0, อังคารคือ 1, ... อาทิตย์คือ 6
เหตุผล: ยอดขายในแต่ละวันของสัปดาห์อาจแตกต่างกัน เช่น ยอดขายช่วงสุดสัปดาห์อาจจะสูงกว่าวันธรรมดา การรู้หมายเลขวันช่วยให้โมเดลพิจารณาความแตกต่างนี้ได้
5. quarter: คอลัมน์นี้เก็บ หมายเลขไตรมาส ของปีครับ ไตรมาส 1 คือ ม.ค.-มี.ค., ไตรมาส 2 คือ เม.ย.-มิ.ย., ไตรมาส 3 คือ ก.ค.-ก.ย., ไตรมาส 4 คือ ต.ค.-ธ.ค.
เหตุผล: บางธุรกิจมียอดขายที่แตกต่างกันอย่างชัดเจนในแต่ละไตรมาส (เช่น ไตรมาส 4 ที่มีเทศกาลสำคัญเยอะ) การรู้ไตรมาสช่วยให้โมเดลเรียนรู้รูปแบบตามไตรมาสได้

### ขั้นตอนที่ 4: การเลือกตัวแปรและแบ่งข้อมูล (Feature Selection and Data Splitting)

เลือกคอลัมน์ที่จะใช้เป็นตัวแปรอิสระ (Features หรือ $X$) ในการทำนาย และคอลัมน์ที่เป็นตัวแปรเป้าหมาย (Target หรือ $y$) คือ `Weekly_Sales`

In [36]:
# Select features (X) and target (y)
# เราจะเลือกคอลัมน์ทั้งหมด ยกเว้น 'Weekly_Sales' (ที่เราต้องการทำนาย)
# และคอลัมน์ 'Date' รวมถึงคอลัมน์ที่ซ้ำซ้อนหรือถูกแปลงไปแล้ว

# Define columns to drop initially
cols_to_drop = ['Weekly_Sales','Date']

# Check if 'IsHoliday_y' exists and add to cols_to_drop if it does
if 'IsHoliday_y' in df.columns:
    cols_to_drop.append('IsHoliday_y')
    print("Dropping 'IsHoliday_y' column as it exists.")
else:
    print("'IsHoliday_y' column not found, skipping drop.")

# Drop the selected columns from df to create X
X = df.drop(cols_to_drop, axis=1)
y = df['Weekly_Sales']

print("ตัวแปรอิสระ (X) 5 แถวแรก:")
display(X.head())

print("\nตัวแปรตาม (y) 5 แถวแรก:")
display(y.head())

'IsHoliday_y' column not found, skipping drop.
ตัวแปรอิสระ (X) 5 แถวแรก:

,Store,Dept,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,...,week,month,year,dayofweek,quarter,Type_A,Type_B,Type_C,IsHoliday_False,IsHoliday_True
0,1,1,42.31,2.572,0.0,0.0,0.0,0.0,0.0,211.096358,...,5,2,2010,4,1,1,0,0,1,0
1,1,1,38.51,2.548,0.0,0.0,0.0,0.0,0.0,211.242170,...,6,2,2010,4,1,1,0,0,0,1
2,1,1,39.93,2.514,0.0,0.0,0.0,0.0,0.0,211.289143,...,7,2,2010,4,1,1,0,0,1,0
3,1,1,46.63,2.561,0.0,0.0,0.0,0.0,0.0,211.319643,...,8,2,2010,4,1,1,0,0,1,0
4,1,1,46.50,2.625,0.0,0.0,0.0,0.0,0.0,211.350143,...,9,3,2010,4,1,1,0,0,1,0

ตัวแปรตาม (y) 5 แถวแรก:

0    24924.50
1    46039.49
2    41595.55
3    19403.54
4    21827.90
Name: Weekly_Sales, dtype: float64

แบ่งข้อมูลออกเป็น 2 ส่วน:
1.  **ชุดฝึกสอน (Training Set):** ใช้สำหรับฝึกตัวแบบ (ประมาณ 80% ของข้อมูล)
2.  **ชุดทดสอบ (Test Set):** ใช้สำหรับประเมินประสิทธิภาพของตัวแบบกับข้อมูลที่ไม่เคยเห็นมาก่อน (ประมาณ 20% ของข้อมูล)

In [37]:
from sklearn.model_selection import train_test_split

# แบ่งข้อมูล X และ y ออกเป็น Training และ Test sets
# test_size=0.2 หมายถึงใช้ 20% ของข้อมูลเป็นชุดทดสอบ
# random_state=42 ช่วยให้การแบ่งข้อมูลเหมือนเดิมทุกครั้งที่รันโค้ด เพื่อผลลัพธ์ที่สอดคล้องกัน
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"\nขนาดของ X_train (สำหรับฝึก): {X_train.shape}")
print(f"ขนาดของ X_test (สำหรับทดสอบ): {X_test.shape}")
print(f"ขนาดของ y_train (สำหรับฝึก): {y_train.shape}")
print(f"ขนาดของ y_test (สำหรับทดสอบ): {y_test.shape}")

ขนาดของ X_train (สำหรับฝึก): (336169, 22)
ขนาดของ X_test (สำหรับทดสอบ): (84043, 22)
ขนาดของ y_train (สำหรับฝึก): (336169,)
ขนาดของ y_test (สำหรับทดสอบ): (84043,)

### ขั้นตอนที่ 5: การสร้างและฝึกตัวแบบ (Build and Train the Model)

สร้าง Object ของ Random Forest Regressor และทำการฝึกด้วยข้อมูล `X_train` และ `y_train`

In [ ]:
from sklearn.ensemble import RandomForestRegressor

# Instantiate the model
# n_estimators คือจำนวนต้นไม้ในป่า (ลองเริ่มที่ 100)
# random_state ช่วยให้ผลการฝึกเหมือนเดิมทุกครั้งที่รัน
# n_jobs=-1 ใช้ CPU ทุก Core เพื่อให้ฝึกเร็วขึ้น
model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)

# Train the model
model.fit(X_train, y_train)

print("Random Forest Regressor Model training complete.")

1. n_estimators=100
อธิบาย: พารามิเตอร์นี้กำหนด จำนวนต้นไม้ตัดสินใจ ที่จะสร้างขึ้นในป่า Random Forest ครับ Random Forest ทำงานโดยการรวมผลการทำนายจากต้นไม้หลายๆ ต้นเข้าด้วยกัน ยิ่งมีต้นไม้เยอะ โมเดลก็มักจะยิ่งแม่นยำและมีความทนทานต่อ Overfitting มากขึ้น

ทำไมใช้ 100: ค่า 100 เป็นค่าเริ่มต้นที่นิยมใช้และมักจะให้ผลลัพธ์ที่ดีในหลายๆ กรณีครับ การเพิ่มจำนวนต้นไม้ให้มากขึ้นกว่านี้ (เช่น 200, 500, 1000) อาจช่วยเพิ่มความแม่นยำได้อีกเล็กน้อย แต่ก็ต้องใช้เวลาในการฝึกและประมวลผลนานขึ้น เราสามารถลองปรับค่านี้เพื่อหาจำนวนต้นไม้ที่เหมาะสมกับข้อมูลและทรัพยากรที่เรามีได้

2. random_state=42
อธิบาย: พารามิเตอร์นี้ใช้สำหรับกำหนด ค่าเริ่มต้นของตัวสร้างเลขสุ่ม (Random Number Generator) ครับ ใน Random Forest มีกระบวนการสุ่มอยู่หลายส่วน เช่น การสุ่มเลือกข้อมูลย่อยเพื่อสร้างแต่ละต้นไม้ และการสุ่มเลือกคุณลักษณะที่จะใช้ในการแบ่งข้อมูล
ทำไมใช้ 42: การกำหนด random_state เป็นค่าคงที่ (เช่น 42 หรือเลขอื่นๆ ที่คุณชอบ) จะทำให้ ผลลัพธ์ของการฝึกโมเดลเหมือนเดิมทุกครั้ง ที่คุณรันโค้ดครับ หากไม่กำหนดค่านี้ ทุกครั้งที่รันโค้ด โมเดลอาจจะได้ต้นไม้ที่แตกต่างกันเล็กน้อยเนื่องจากการสุ่ม ทำให้ผลการทำนายอาจเปลี่ยนแปลงไปได้
เหตุผล: การกำหนด random_state มีประโยชน์มากในการทดลองและพัฒนาโมเดลครับ เพราะช่วยให้เรามั่นใจได้ว่าการเปลี่ยนแปลงใดๆ ในโค้ด (เช่น การเตรียมข้อมูล หรือการปรับ Hyperparameters อื่นๆ) คือสาเหตุที่แท้จริงที่ทำให้ผลลัพธ์เปลี่ยนไป ไม่ใช่เพราะการสุ่มที่แตกต่างกันในแต่ละครั้งครับ เลข 42 เป็นเลขที่นิยมใช้ในวงการ Data Science

3. n_jobs=-1
อธิบาย: พารามิเตอร์นี้กำหนดว่าเราต้องการให้โมเดลใช้ จำนวน Core ของ CPU ในการทำงานเท่าไหร่ครับ
ทำไมใช้ -1: ค่า -1 เป็นค่าพิเศษที่หมายถึง ให้ใช้ Core ของ CPU ทั้งหมดที่มีอยู่ ครับ การฝึกโมเดล Random Forest สามารถทำแบบขนานได้ (ฝึกแต่ละต้นไม้แยกกัน) การใช้ Core ทั้งหมดจะช่วยให้กระบวนการฝึกโมเดลเสร็จเร็วขึ้นอย่างมาก โดยเฉพาะเมื่อมีจำนวนต้นไม้เยอะๆ หรือข้อมูลมีขนาดใหญ่ค

**สรุปคือ** พารามิเตอร์เหล่านี้ช่วยให้เราควบคุมลักษณะของโมเดล Random Forest ครับ n_estimators กำหนดขนาดของป่า (จำนวนต้นไม้), random_state ช่วยให้ผลลัพธ์คงที่สำหรับการทดลอง และ n_jobs ช่วยให้การฝึกโมเดลเร็วขึ้นครับ ค่าที่ใช้ (100, 42, -1) เป็นค่าเริ่มต้นที่นิยมและเหมาะสมสำหรับการเริ่มต้น

### ขั้นตอนที่ 6: การประเมินประสิทธิภาพของตัวแบบ (Model Evaluation)

ใช้ Metric มาตรฐานสำหรับ Regression (MAE, MSE, RMSE) ในการวัดว่าตัวแบบทำนายได้แม่นยำแค่ไหนเมื่อเทียบกับค่าจริงในข้อมูลชุดทดสอบครับ

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

# Make predictions on the test set
predictions = model.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, predictions)
mse = mean_squared_error(y_test, predictions)
rmse = np.sqrt(mse)

print(f"Mean Absolute Error (MAE): {mae}")
print(f"Mean Squared Error (MSE): {mse}")
print(f"Root Mean Squared Error (RMSE): {rmse}")

การจะบอกว่าค่าความคลาดเคลื่อนของโมเดล Regression นั้น "น้อย" หรือ "มาก" จะต้องพิจารณาเปรียบเทียบกับ ขนาด (Scale) และ ความแปรปรวน (Variability) ของตัวแปรเป้าหมายที่เรากำลังทำนายครับ ซึ่งในกรณีนี้คือ Weekly_Sales (ยอดขายรายสัปดาห์) ครับ

ลองดูข้อมูลสถิติสรุปของคอลัมน์ Weekly_Sales ที่เราแสดงใน Cell a9bd22f7 อีกครั้งนะครับ

จาก df.describe() เราเห็นว่า:

* ค่าเฉลี่ย (mean) ของ Weekly_Sales อยู่ที่ประมาณ 15,981.26
* ค่าเบี่ยงเบนมาตรฐาน (std) ของ Weekly_Sales อยู่ที่ประมาณ 22,717.78 (ค่านี้บอกว่ายอดขายโดยทั่วไปกระจายตัวห่างจากค่าเฉลี่ยประมาณเท่าไหร่)
ช่วงของค่า (min ถึง max) ของ Weekly_Sales กว้างมาก ตั้งแต่ 0.01 ถึง 693,099.36

Metric ที่ได้จากการประเมินโมเดล:

* Mean Absolute Error (MAE) = 1442.25

อธิบาย: MAE บอกค่าความคลาดเคลื่อน "โดยเฉลี่ย" ระหว่างยอดขายจริงกับยอดขายที่โมเดลทำนายได้ครับ
ทำไมถึงน้อย: การที่โมเดลทำนายคลาดเคลื่อนไปโดยเฉลี่ยประมาณ 1,442.25 หน่วย ถือว่าน้อยมากๆ เมื่อเทียบกับยอดขายโดยเฉลี่ยที่เกือบ 16,000 หน่วย หรือเมื่อเทียบกับยอดขายสูงสุดที่เกือบ 7 แสนหน่วยครับ คิดเป็นเปอร์เซ็นต์ความคลาดเคลื่อนเฉลี่ย (เมื่อเทียบกับยอดขายเฉลี่ย) ก็จะอยู่ที่ประมาณ (1442.25 / 15981.26) * 100% = ประมาณ 9% ซึ่งถือว่าค่อนข้างต่ำสำหรับงานทำนายยอดขายที่มีความผันผวนสูง
* Root Mean Squared Error (RMSE) = 3523.21
อธิบาย: RMSE ก็บอกค่าความคลาดเคลื่อนเช่นกัน แต่จะให้น้ำหนักกับข้อผิดพลาดที่มากๆ (ข้อผิดพลาดที่คลาดเคลื่อนไปเยอะๆ) มากกว่า MAE มีหน่วยเดียวกับตัวแปรเป้าหมาย ทำให้ตีความได้ง่าย
ทำไมถึงน้อย: ค่า RMSE ที่ประมาณ 3,523.21 ก็ยังถือว่าน้อยกว่าค่าเบี่ยงเบนมาตรฐานของยอดขาย (22,717.78) มาก หมายความว่าการทำนายของโมเดลมีความผันผวนของข้อผิดพลาดน้อยกว่าความผันผวนของยอดขายจริง

### ขั้นตอนที่ 7: การดูความสำคัญของคุณลักษณะ (Feature Importance)

ดูว่าคุณลักษณะ (Feature) ตัวไหนมีความสำคัญมากที่สุดในการทำนายยอดขายตามที่ตัวแบบ Random Forest เรียนรู้มา

In [ ]:
# Get feature importances from the trained model
feature_importances = pd.Series(model.feature_importances_, index=X.columns).sort_values(ascending=False)

print("\nFeature Importances:")
display(feature_importances)

# Optional: Visualize feature importances
plt.figure(figsize=(12, 8))
sns.barplot(x=feature_importances, y=feature_importances.index)
plt.title('Feature Importances from Random Forest Regressor')
plt.xlabel('Importance')
plt.ylabel('Feature')
plt.show()

### ขั้นตอนที่ 8: การวิเคราะห์ Residuals (Error Analysis)

ตรวจสอบความแตกต่างระหว่างค่าจริงและค่าทำนาย (Residuals) เพื่อดูว่าตัวแบบของเรามีข้อผิดพลาดที่เป็นระบบหรือไม่

In [ ]:
# Calculate residuals
residuals = y_test - predictions

# Plot residuals
plt.figure(figsize=(10, 6))
plt.scatter(predictions, residuals, alpha=0.5)
plt.xlabel("Predicted Weekly Sales")
plt.ylabel("Residuals (Actual - Predicted)")
plt.title("Residual Plot")
plt.hlines(0, plt.xlim()[0], plt.xlim()[1], color='red', linestyles='--')
plt.show()

# Optional: Distribution of residuals
plt.figure(figsize=(10, 6))
sns.histplot(residuals, kde=True)
plt.title("Distribution of Residuals")
plt.xlabel("Residuals")
plt.ylabel("Frequency")
plt.show()

เราได้สร้างกราฟ 2 แบบ:
1.  **Residual Plot:** กราฟที่แสดงความสัมพันธ์ระหว่างค่าทำนาย (Predicted Weekly Sales) กับค่า Residuals (Actual - Predicted)
2.  **Histogram of Residuals:** กราฟที่แสดงการกระจายตัวของค่า Residuals

**การตีความจากกราฟ:**
*   **Residual Plot:** หากตัวแบบทำนายได้ดีและไม่มีข้อผิดพลาดที่เป็นระบบ จุดในกราฟ Residual Plot ควรจะกระจายตัวแบบสุ่มรอบๆ เส้นศูนย์ (เส้นสีแดง)แต่หากเห็นรูปแบบที่ชัดเจน เช่น จุดเรียงตัวเป็นรูปกรวย หรือมีกลุ่มจุดที่อยู่ห่างจากเส้นศูนย์มาก แสดงว่าตัวแบบอาจมีปัญหาในการทำนายค่าบางช่วง
*   **Histogram of Residuals:** หากข้อผิดพลาดเป็นการสุ่ม การกระจายตัวของ Residuals ควรมีลักษณะใกล้เคียง Normal Distribution (รูประฆังคว่ำ) ที่มีค่าเฉลี่ยใกล้เคียงศูนย์ครับ การที่กราฟเบ้ไปทางใดทางหนึ่ง หรือมีหลายยอด อาจบ่งชี้ถึงปัญหาในการทำนายครับ

### ขั้นตอนที่ 9: การทำนายข้อมูลทดสอบ (Prediction on Test Data)

เตรียมข้อมูลจาก `test.csv` ให้มีรูปแบบเหมือนกับข้อมูลฝึกสอน (`X_train`) และใช้ตัวแบบ Random Forest Regressor ที่ฝึกแล้วในการทำนายยอดขาย

In [ ]:
# Load the actual test data
test_df = pd.read_csv(test_path)

# Merge with features and stores data, similar to how the training data was merged
test_df = test_df.merge(df_ft, on=['Store', 'Date'], how='inner').merge(df_st, on=['Store'], how='inner')

# Handle missing values in MarkDown columns (fill with 0)
markdown_cols = ['MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5']
test_df[markdown_cols] = test_df[markdown_cols].fillna(0)

# Create date-related features
test_df["Date"] = pd.to_datetime(test_df["Date"])
test_df['week'] = test_df['Date'].dt.isocalendar().week.astype(int)
test_df['month'] = test_df['Date'].dt.month
test_df['year'] = test_df['Date'].dt.year
test_df['dayofweek'] = test_df['Date'].dt.dayofweek
test_df['quarter'] = test_df['Date'].dt.quarter

# Perform One-Hot Encoding for 'Type' and 'IsHoliday' (Note: test.csv uses 'IsHoliday', not 'IsHoliday_x')
test_df = pd.get_dummies(test_df, columns=['Type'], prefix='Type')
if 'IsHoliday' in test_df.columns: # Use 'IsHoliday' column from test.csv
    test_df = pd.get_dummies(test_df, columns=['IsHoliday'], prefix='IsHoliday_x') # Rename to match training data column prefix

# Drop the original 'Date' column and potentially redundant 'IsHoliday' column if it exists and wasn't encoded
test_df = test_df.drop(['Date'], axis=1)
if 'IsHoliday' in test_df.columns: # Drop original 'IsHoliday' if still exists after encoding
    test_df = test_df.drop(['IsHoliday'], axis=1)


# Ensure test_df has the exact same columns as X_train, fill missing columns with 0 if any
missing_cols_in_test = set(X_train.columns) - set(test_df.columns)
for c in missing_cols_in_test:
    test_df[c] = 0

# Ensure the order of columns in test_df is the same as X_train
test_df = test_df[X_train.columns]

print("Processed test data head (ready for prediction):")
display(test_df.head())

In [ ]:
# Make predictions on the prepared test data
final_test_predictions = model.predict(test_df)

print("\nFinal predictions on the test data:")
display(final_test_predictions)

# พบว่า feature importance มีค่าใกล้ศูนย์จำนวนมาก จึงทำการทดสอบอีกครั้งโดยการเลือกตัวแปรที่มีค่าfeature importanceสูง

### ขั้นตอนที่ 10: การเลือกคุณลักษณะ (Feature Selection) โดยใช้ Feature Importance จากโมเดลรอบแรก

ในขั้นตอนนี้ เราจะใช้ค่าความสำคัญของคุณลักษณะ (Feature Importance) ที่ได้จากตัวแบบ Random Forest ที่ฝึกไปแล้ว (ในขั้นตอนที่ 5) มาช่วยในการเลือกคุณลักษณะ (Features) ที่มีอิทธิพลต่อการทำนายยอดขายมากที่สุด

เราจะแสดงค่า Feature Importance เป็นกราฟเส้น และพิจารณาหาจุด "ข้อศอก" (Elbow Point) บนกราฟ เพื่อช่วยตัดสินใจว่าจะเลือกคุณลักษณะกี่ตัวที่มีความสำคัญสูงสุดไปใช้ในการสร้างโมเดลรอบสอง

**เหตุผล:** การเลือกเฉพาะคุณลักษณะที่สำคัญ อาจช่วยให้โมเดลรอบสองมีประสิทธิภาพดีขึ้น ลดความซับซ้อน และฝึกได้เร็วขึ้น

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# ตรวจสอบว่ามี 'model' และ 'X' จากขั้นตอนก่อนหน้า
if 'model' not in locals():
    print("Error: Model object 'model' not found. Please ensure steps 1-5 were run successfully.")
elif 'X' not in locals():
    print("Error: DataFrame X not found. Please ensure previous steps (especially data splitting) were run.")
else:
    # คำนวณ Feature Importances
    # (เราจะเก็บตัวแปร feature_importances นี้ไว้ใช้ในเซลล์ถัดไป)
    feature_importances = pd.Series(model.feature_importances_, index=X.columns).sort_values(ascending=False)

    print("Feature Importances (from initial model):")

    # พล็อตกราฟ Feature Importances เพื่อหาจุดข้อศอก
    plt.figure(figsize=(14, 7))

    # 1. เพิ่ม marker='o' เพื่อให้มี "จุด"
    sns.lineplot(x=range(len(feature_importances)),
                 y=feature_importances.values,
                 marker='o',
                 markersize=8)

    # 2. เพิ่ม plt.xticks เพื่อให้แสดงตัวเลข Rank (0, 1, 2, ...) ทุกจุด
    plt.xticks(ticks=np.arange(len(feature_importances)))

    plt.title('Feature Importances Ranked')
    plt.xlabel('Rank of Feature')
    plt.ylabel('Importance Score')
    plt.grid(True)
    plt.show()

    print("\nพิจารณากราฟด้านบนเพื่อหาจุด 'ข้อศอก' (Elbow Point)")
    print("จากกราฟ, จุดที่เหมาะสมดูเหมือนจะเป็น Rank 4 (ซึ่งคือ 5 ตัวแรก)")

เนื่องจากสังเกตุว่าจุดที่ 5 เหมาะสมที่จะเป็นจุดหักศอกมากที่สุด

In [ ]:
# ตรวจสอบว่าตัวแปรจากเซลล์ก่อนหน้าพร้อมใช้งาน
if 'feature_importances' not in locals():
     print("Error: 'feature_importances' not found. กรุณารันเซลล์ด้านบนก่อนครับ")
elif 'df' not in locals() or df is None:
     print("Error: DataFrame 'df' not found. กรุณาตรวจสอบว่าโหลดข้อมูลแล้ว")
else:

    # --- ส่วนที่แก้ไข ---
    # เรากำหนดค่า '5' ลงไปเลย โดยไม่ต้องรอ input
    # (อ้างอิงจากกราฟที่ Rank 4 คือจุดหักศอก ซึ่งหมายถึง 5 feature แรก: 0, 1, 2, 3, 4)
    num_top_features = 5
    print(f"กำหนดค่าตายตัว: เลือก Feature ที่สำคัญสูงสุด {num_top_features} ตัว")
    # -------------------

    # ดึงรายชื่อของ feature ที่สำคัญ 5 อันดับแรก
    selected_features = feature_importances.head(num_top_features).index.tolist()

    print(f"\nFeatures ที่เลือก {num_top_features} ตัว ได้แก่:")
    print(selected_features)

    # สร้าง X_selected และ y_selected ใหม่ โดยใช้เฉพาะ feature ที่เลือก
    X_selected = df[selected_features].copy()
    y_selected = df['Weekly_Sales'].copy()

    print(f"\nใหม่: ตัวแปรอิสระ (X_selected) หลังเลือก Feature (5 แถวแรก):")
    display(X_selected.head())

    print(f"\nขนาดของ X_selected: {X_selected.shape}")
    print(f"ขนาดของ y_selected: {y_selected.shape}")

    print("\n====== สรุปผลการเลือกคุณลักษณะ: เลือก Feature ที่สำคัญสำเร็จ ======")

### ขั้นตอนที่ 11: การแบ่งข้อมูล (Data Splitting) ด้วยคุณลักษณะที่เลือกแล้ว

นำตัวแปรอิสระที่เลือกแล้ว (`X_selected`) และตัวแปรเป้าหมาย (`y_selected`) มาแบ่งออกเป็นชุดฝึกสอน (Training Set) และชุดทดสอบ (Test Set) อีกครั้ง เพื่อใช้ในการฝึกตัวแบบ Random Forest รอบที่สองครับ

In [ ]:
from sklearn.model_selection import train_test_split

# Ensure X_selected and y_selected are defined
if 'X_selected' in locals() and 'y_selected' in locals():
    # แบ่งข้อมูล X_selected และ y_selected ออกเป็น Training และ Test sets
    # ใช้ test_size และ random_state เหมือนเดิมเพื่อให้เปรียบเทียบได้
    X_train_selected, X_test_selected, y_train_selected, y_test_selected = train_test_split(X_selected, y_selected, test_size=0.2, random_state=42)

    print(f"\nขนาดของ X_train (หลังเลือก Feature): {X_train_selected.shape}")
    print(f"ขนาดของ X_test (หลังเลือก Feature): {X_test_selected.shape}")
    print(f"ขนาดของ y_train (หลังเลือก Feature): {y_train_selected.shape}")
    print(f"ขนาดของ y_test (หลังเลือก Feature): {y_test_selected.shape}")

    print("\n====== สรุปผลการแบ่งข้อมูล: แบ่งข้อมูลด้วย Feature ที่เลือกสำเร็จ ======")

else:
    print("ตัวแปร X_selected หรือ y_selected ยังไม่ได้ถูกสร้างขึ้น โปรดตรวจสอบขั้นตอนที่ 10")

### ขั้นตอนที่ 12: การสร้างและฝึกตัวแบบ Random Forest Regressor รอบที่สอง

สร้าง Object ของ Random Forest Regressor อีกครั้ง และทำการฝึกด้วยข้อมูลชุดฝึกสอนที่ใช้เฉพาะคุณลักษณะที่เลือกแล้ว (`X_train_selected` และ `y_train_selected`)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

# Instantiate the second model
# ใช้ hyperparameters เดียวกันกับโมเดลแรก เพื่อให้เปรียบเทียบผลกระทบของการเลือก Feature ได้ชัดเจน
model_selected_features = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)

# Ensure X_train_selected and y_train_selected are defined
if 'X_train_selected' in locals() and 'y_train_selected' in locals():
    # Train the second model with selected features
    model_selected_features.fit(X_train_selected, y_train_selected)

    print("Random Forest Regressor Model (with selected features) training complete.")
    print("\n====== สรุปผลการฝึกตัวแบบ: ฝึกโมเดลรอบสองสำเร็จ ======")

else:
    print("ตัวแปร X_train_selected หรือ y_train_selected ยังไม่ได้ถูกสร้างขึ้น โปรดตรวจสอบขั้นตอนที่ 11")

### ขั้นตอนที่ 13: การประเมินประสิทธิภาพของตัวแบบรอบที่สอง (Model Evaluation - Selected Features)

ใช้ Metric มาตรฐาน (MAE, MSE, RMSE) ในการวัดว่าตัวแบบ Random Forest รอบที่สองที่ใช้คุณลักษณะที่เลือกแล้ว ทำนายได้แม่นยำแค่ไหนเมื่อเทียบกับค่าจริงในข้อมูลชุดทดสอบ

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

# Ensure model_selected_features, X_test_selected, and y_test_selected are defined
if 'model_selected_features' in locals() and 'X_test_selected' in locals() and 'y_test_selected' in locals():
    # Make predictions on the test set with selected features
    predictions_selected = model_selected_features.predict(X_test_selected)

    # Evaluate the second model
    mae_selected = mean_absolute_error(y_test_selected, predictions_selected)
    mse_selected = mean_squared_error(y_test_selected, predictions_selected)
    rmse_selected = np.sqrt(mse_selected)

    print(f"Mean Absolute Error (MAE) (Selected Features): {mae_selected}")
    print(f"Mean Squared Error (MSE) (Selected Features): {mse_selected}")
    print(f"Root Mean Squared Error (RMSE) (Selected Features): {rmse_selected}")

    print("\n====== สรุปผลการประเมินตัวแบบรอบสอง: ประเมินสำเร็จ ======")

    # Optional: Compare with the first model's performance
    if 'mae' in locals() and 'mse' in locals() and 'rmse' in locals():
        print("\n====== การเปรียบเทียบกับตัวแบบแรก (ใช้ Feature ทั้งหมด) ======")
        print(f"ตัวแบบแรก: MAE={mae}, MSE={mse}, RMSE={rmse}")
        print(f"ตัวแบบรอบสอง (Selected Features): MAE={mae_selected}, MSE={mse_selected}, RMSE={rmse_selected}")
        print("==========================================================")
        if mae_selected < mae:
            print(">>> MAE ลดลง: การเลือก Feature ช่วยให้ความคลาดเคลื่อนเฉลี่ยน้อยลง")
        elif mae_selected > mae:
             print(">>> MAE เพิ่มขึ้น: การเลือก Feature อาจทำให้ความคลาดเคลื่อนเฉลี่ยมากขึ้น")
        else:
             print(">>> MAE เท่าเดิม")

        if rmse_selected < rmse:
            print(">>> RMSE ลดลง: การเลือก Feature ช่วยลดความคลาดเคลื่อนรวม")
        elif rmse_selected > rmse:
             print(">>> RMSE เพิ่มขึ้น: การเลือก Feature อาจทำให้ความคลาดเคลื่อนรวมมากขึ้น")
        else:
             print(">>> RMSE เท่าเดิม")
    else:
        print("\nไม่พบ Metric ของตัวแบบแรก ไม่สามารถเปรียบเทียบได้")


else:
    print("ตัวแปรโมเดลรอบสอง หรือข้อมูลทดสอบที่เลือก Feature ยังไม่ได้ถูกสร้างขึ้น โปรดตรวจสอบขั้นตอนที่ 11 และ 12")

### ขั้นตอนที่ 14: การทำนายข้อมูลทดสอบ (Prediction on Test Data) ด้วยตัวแบบรอบที่สอง

เตรียมข้อมูลจาก `test.csv` ให้มีรูปแบบเหมือนข้อมูลฝึกสอนที่ใช้ในการสร้างตัวแบบรอบที่สอง (คือใช้เฉพาะคุณลักษณะที่เลือกแล้ว) และใช้ตัวแบบ Random Forest Regressor รอบที่สองในการทำนายยอดขายครับ

In [ ]:
# Load the original test data again to get Store, Dept, Date columns
# We use the original test_path
original_test_df = pd.read_csv(test_path)

# Re-merge with features and stores data, similar to how the training data was merged
test_df_for_prediction_selected = original_test_df.merge(df_ft, on=['Store', 'Date'], how='inner').merge(df_st, on=['Store'], how='inner')

# Handle missing values in MarkDown columns (fill with 0)
markdown_cols = ['MarkDown1', 'MarkDown2', 'MarkDown3', 'MarkDown4', 'MarkDown5']
# Ensure markdown columns exist before filling NaNs
existing_markdown_cols_test = [col for col in markdown_cols if col in test_df_for_prediction_selected.columns]
if existing_markdown_cols_test:
    test_df_for_prediction_selected[existing_markdown_cols_test] = test_df_for_prediction_selected[existing_markdown_cols_test].fillna(0)
else:
    print("Warning: No MarkDown columns found in the merged test data.")


# Create date-related features
# Ensure 'Date' column exists before proceeding
if 'Date' in test_df_for_prediction_selected.columns:
    try:
        test_df_for_prediction_selected["Date"] = pd.to_datetime(test_df_for_prediction_selected["Date"])
        test_df_for_prediction_selected['week'] = test_df_for_prediction_selected['Date'].dt.isocalendar().week.astype(int)
        test_df_for_prediction_selected['month'] = test_df_for_prediction_selected['Date'].dt.month
        test_df_for_prediction_selected['year'] = test_df_for_prediction_selected['Date'].dt.year
        test_df_for_prediction_selected['dayofweek'] = test_df_for_prediction_selected['Date'].dt.dayofweek
        test_df_for_prediction_selected['quarter'] = test_df_for_prediction_selected['Date'].dt.quarter
    except Exception as e:
        print(f"\nเกิดข้อผิดพลาดในการสร้าง Feature จากวันที่สำหรับข้อมูลทดสอบ: {e}")
else:
    print("Warning: 'Date' column not found in merged test data for creating date features.")


# Perform One-Hot Encoding for 'Type' and 'IsHoliday'
# Ensure 'Type' column exists
if 'Type' in test_df_for_prediction_selected.columns:
    test_df_for_prediction_selected = pd.get_dummies(test_df_for_prediction_selected, columns=['Type'], prefix='Type')
else:
     print("Warning: 'Type' column not found in merged test data for encoding.")


# Handle 'IsHoliday' from test.csv
# test.csv has 'IsHoliday', not 'IsHoliday_x' or 'IsHoliday_y'
if 'IsHoliday' in test_df_for_prediction_selected.columns:
     test_df_for_prediction_selected = pd.get_dummies(test_df_for_prediction_selected, columns=['IsHoliday'], prefix='IsHoliday') # Use prefix 'IsHoliday'

     # Ensure the encoded columns are integers if needed to match training data
     if 'IsHoliday_False' in test_df_for_prediction_selected.columns:
         test_df_for_prediction_selected['IsHoliday_False'] = test_df_for_prediction_selected['IsHoliday_False'].astype(int)
     if 'IsHoliday_True' in test_df_for_prediction_selected.columns:
         test_df_for_prediction_selected['IsHoliday_True'] = test_df_for_prediction_selected['IsHoliday_True'].astype(int)

else:
    print("Warning: 'IsHoliday' column not found in merged test data for encoding.")


# Now, select ONLY the features that were used in the second model (X_selected)
# Ensure selected_features list is available from step 10
if 'selected_features' in locals():
    # Add any missing columns in test_df_for_prediction_selected that are in selected_features and fill with 0
    missing_cols_in_test_selected = set(selected_features) - set(test_df_for_prediction_selected.columns)
    for c in missing_cols_in_test_selected:
        test_df_for_prediction_selected[c] = 0
        print(f"Added missing column '{c}' to test data and filled with 0.")


    # Ensure the order of columns in test_df_for_prediction_selected is the same as selected_features
    # This is CRUCIAL for prediction
    test_df_for_prediction_selected = test_df_for_prediction_selected[selected_features]

    print("\nProcessed test data head (ready for prediction with selected features):")
    display(test_df_for_prediction_selected.head())

    print(f"\nขนาดของข้อมูลทดสอบที่เตรียมแล้ว (สำหรับทำนายด้วย Feature ที่เลือก): {test_df_for_prediction_selected.shape}")
    print("\n====== สรุปผลการเตรียมข้อมูลทดสอบ: เตรียมสำเร็จ ======")

else:
    print("รายการคุณลักษณะที่เลือก 'selected_features' ยังไม่ได้ถูกสร้างขึ้น โปรดตรวจสอบขั้นตอนที่ 10")

In [ ]:
# Make predictions on the prepared test data using the second model
# Ensure model_selected_features and test_df_for_prediction_selected are defined
if 'model_selected_features' in locals() and 'test_df_for_prediction_selected' in locals():
    final_test_predictions_selected = model_selected_features.predict(test_df_for_prediction_selected)

    print("\nFinal predictions on the test data (using model with selected features):")
    display(final_test_predictions_selected)

    print("\n====== สรุปผลการทำนาย: ทำนายด้วยโมเดลรอบสองสำเร็จ ======")

else:
    print("ตัวแปรโมเดลรอบสอง หรือข้อมูลทดสอบที่เลือก Feature ยังไม่ได้ถูกสร้างขึ้น โปรดตรวจสอบขั้นตอนที่ 12 และขั้นตอนการเตรียมข้อมูลทดสอบ")

### ขั้นตอนที่ 15: การเตรียมผลการทำนายจากตัวแบบรอบที่สอง (Prepare Predictions - Second Model)

นำค่าทำนายที่ได้จากตัวแบบ Random Forest รอบที่สอง (`final_test_predictions_selected`) ไปรวมกับข้อมูลระบุรายการ (Store, Dept, Date) จากไฟล์ `test.csv` เพื่อสร้าง DataFrame ผลลัพธ์ครับ

In [ ]:
# Load the original test data again to get Store, Dept, Date columns
# We use the original test_path
original_test_df = pd.read_csv(test_path)

# Create the 'Id' column for submission format
original_test_df['Id'] = original_test_df['Store'].astype(str) + '_' + original_test_df['Dept'].astype(str) + '_' + original_test_df['Date']

# The predictions 'final_test_predictions_selected' are in the order of the 'test_df_for_prediction_selected' used in step 14.
# We need to ensure the submission dataframe has the same rows in the same order to match predictions.
# The 'test_df_for_prediction_selected' in step 14 was created by merging original test data, features, and stores.

# Recreate the merged test_df that was used for prediction in step 14
test_df_predicted_rows_selected = pd.read_csv(test_path).merge(df_ft, on=['Store', 'Date'], how='inner').merge(df_st, on=['Store'], how='inner')

# Ensure the order matches the order used for prediction in step 14
# Assuming the processing in step 14 didn't reorder rows other than implicit inner join effects.
# Create the ID for these predicted rows
test_df_predicted_rows_selected['Id'] = test_df_predicted_rows_selected['Store'].astype(str) + '_' + test_df_predicted_rows_selected['Dept'].astype(str) + '_' + test_df_predicted_rows_selected['Date']

# Create the submission dataframe structure with Id and Weekly_Sales
submission_df_selected = pd.DataFrame({'Id': test_df_predicted_rows_selected['Id'], 'Weekly_Sales': final_test_predictions_selected})

print("Submission DataFrame head (from second model):")
display(submission_df_selected.head())

print("\n====== สรุปผลการเตรียมผลการทำนาย: เตรียมสำเร็จ ======")

# ความสัมพันธ์ระหว่างตัวแปรกับยอดขาย

In [ ]:
# Merge data: train + features + stores
# ใช้ how='inner' เพื่อรวมเฉพาะแถวที่มี Store และ Date ตรงกันใน train และ features
# และรวมกับ stores โดยใช้ Store ที่ตรงกัน
df = train.merge(df_ft, on=['Store', 'Date'], how='inner').merge(df_st, on=['Store'], how='inner')

print("\nข้อมูลที่รวมกันแล้ว (5 แถวแรก):")
display(df.head())

print("\nขนาดของข้อมูลที่รวมกันแล้ว:")
display(df.shape)

#### กราฟความสัมพันธ์ระหว่าง CPI (ดัชนีราคาผู้บริโภค) กับยอดขาย

In [ ]:
# Scatter plot of CPI vs Weekly_Sales
plt.figure(figsize=(10, 6))
sns.scatterplot(x='CPI', y='Weekly_Sales', data=df, alpha=0.6)
plt.title('Weekly Sales vs CPI')
plt.xlabel('CPI')
plt.ylabel('Weekly Sales')
plt.grid(True)
plt.show()

#### กราฟความสัมพันธ์ระหว่างอุณหภูมิ (Temperature) กับยอดขาย

In [ ]:
# Bar plot or line plot of average Weekly_Sales by week of the year
plt.figure(figsize=(14, 7))
# Use .agg('mean') with as_index=False to keep 'week' as a column
sns.lineplot(x='week', y='Weekly_Sales', data=df.groupby('week', as_index=False)['Weekly_Sales'].agg('mean'))
plt.title('Average Weekly Sales by Week of Year')
plt.xlabel('Week of Year')
plt.ylabel('Average Weekly Sales')
plt.grid(True)
plt.show()

#### กราฟแสดงยอดขายเฉลี่ยตามสัปดาห์ของปี (Week)

In [ ]:
# Bar plot or line plot of average Weekly_Sales by week of the year
plt.figure(figsize=(14, 7))
sns.lineplot(x='week', y='Weekly_Sales', data=df.groupby('week')['Weekly_Sales'].mean().reset_index())
plt.title('Average Weekly Sales by Week of Year')
plt.xlabel('Week of Year')
plt.ylabel('Average Weekly Sales')
plt.grid(True)
plt.show()